on:
  schedule:
    - cron:  '10 12 * * *'
name: Send Daily Email
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Pull
      run: npm run email
      env:
        MAILCHIMP_TOKEN: ${{ secrets.MAILCHIMP_TOKEN }}
